---
title: "Untitled"
format: html
editor: visual
---

## Checking model assumptions

```{r}
#| label: set-up
#| echo: false
#| warning: false
#| message: false

library(targets)
library(tarchetypes)
library(tidyverse)
library(performance)
library(see)
library(DHARMa)

```

## Multifunctionality

### Number of functional groups present
```{r}
#| label: multifun-nr-check
#| echo: false
#| results: asis
#| message: false

tar_load(model_multifun)

model_multifun |> 
  #mutate(check = map(model, check_model)) |> 
mutate(check = map(model, ~ plot(simulateResiduals(.)))) |> 
  select(check) |> 
  pwalk(.f = function(check, ...){
  #cat(paste("##", "multifun nr fg"))
  print(check)
  cat("\n")
})
  
```


### Treatment effect
```{r}
#| label: multifun-trt-check
#| echo: false
#| results: asis
#| message: false

model_multifun |> 
  #mutate(check = map(model_treatment, check_model)) |> 
  mutate(check = map(model_treatment, ~ plot(simulateResiduals(.)))) |> 
  select(check) |> 
  pwalk(.f = function(check, ...){
  #cat(paste("##", "multifun treatment"))
  print(check)
  cat("\n")
})
  
```


### Factorial approach
```{r}
#| label: multifun-factorial-check
#| echo: false
#| results: asis
#| message: false

model_multifun |> 
  #mutate(check = map(model_treatment, check_model)) |> 
  mutate(check = map(model_factorial, ~ plot(simulateResiduals(.)))) |> 
  select(check) |> 
  pwalk(.f = function(check, ...){
  print(check)
  cat("\n")
})
  
```

## Singe function analyses

```{r}
#| label: response-check
#| echo: false
#| message: false

tar_load(model_response)

model_response |> 
  pwalk(function(response, model, ...) {
    plot(simulateResiduals(model), title = response)
  })
```